import type { ConfidenceLabel } from '../types'

const labels: Record<string, string> = {
  HIGH_OFFICIAL_MATCH: 'Khớp chuẩn',
  REVIEW_REQUIRED: 'Cần kiểm tra',
  INSUFFICIENT_EVIDENCE: 'Chưa đủ chứng cứ',
  BLOCKED: 'Đã tạm khóa',
  OTC: 'Không kê đơn (OTC)',
  PRESCRIPTION: 'Kê đơn (Rx)',
  UNKNOWN: 'Chưa rõ',
  ACTIVE: 'Đang lưu hành',
  RECALLED: 'Thu hồi khẩn cấp',
  QUALITY_VIOLATION: 'Vi phạm chất lượng',
  EXPIRED: 'Hết hạn',
  CRITICAL: 'Nguy cấp',
  HIGH: 'Cao',
  MEDIUM: 'Trung bình',
  LOW: 'Thấp',
  SUCCESS: 'Thành công',
  FAILED: 'Thất bại',
  RUNNING: 'Đang xử lý',
  QUEUED: 'Đang chờ',
  PARTIAL: 'Một phần',
  PENDING: 'Chờ xác nhận',
  CONFIRMED: 'Đã xác nhận',
  PROCESSING: 'Đang đóng gói',
  SHIPPING: 'Đang giao hàng',
  COMPLETED: 'Đã giao thành công',
  DELIVERED: 'Đã giao thành công',
  CANCELLED: 'Đã hủy',
  PAID: 'Đã thanh toán',
  UNPAID: 'Chưa thanh toán',
  EXTRACTED: 'Mới thu thập',
  MATCHED: 'Đã ghép thuốc',
  REJECTED: 'Đã từ chối',
  OPEN: 'Chờ xử lý',
  RESOLVED: 'Đã xử lý xong',
  DISMISSED: 'Đã bỏ qua',
  PUBLISHED: 'Đang bán',
  DRAFT: 'Bản nháp',
  MANUAL_REVIEW: 'Duyệt thủ công',
  AUTO_PUBLISH_VALID: 'Tự động xuất bản',
  REGULATORY: 'Cục Quản lý Dược',
  MANUFACTURER: 'Nhà sản xuất',
  RETAILER: 'Nhà thuốc bán lẻ',
  APPROVED_LEAFLET: 'Hướng dẫn sử dụng',
  MANUAL_UPLOAD: 'Tải tệp thủ công',
  STRENGTH_MISMATCH: 'Lệch hàm lượng',
  MANUFACTURER_MISMATCH: 'Khác nhà sản xuất',
  INGREDIENT_MISMATCH: 'Khác hoạt chất',
  DOSAGE_FORM_MISMATCH: 'Khác dạng bào chế',
  FORM_MISMATCH: 'Khác dạng bào chế',
}

export function StatusBadge({ value }: { value: ConfidenceLabel | string }) {
  const text = labels[value] || value
  return <span className={`badge badge-${String(value).toLowerCase()}`}>{text}</span>
}

